# Generated by Django 3.2.6 on 2021-09-09 00:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Localidad')),
                ('cp', models.CharField(max_length=10, verbose_name='Codigo Postal')),
            ],
            options={
                'verbose_name_plural': 'Localidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('num_doc', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Documento')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Persona/s')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido Persona/s')),
                ('fecha_nac', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Nacimiento')),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='persona_localidad', to='tienda.localidad')),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
