# Generated by Django 3.2.6 on 2021-09-10 22:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.IntegerField(verbose_name='Identificador de articulo')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca de Articulo')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion de Articulo')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria de Articulo')),
                ('stock', models.IntegerField(verbose_name='Stock de Articulo')),
                ('precio', models.FloatField(verbose_name='Precio de Articulo')),
                ('disponible', models.BooleanField(default=False, verbose_name='Disponibilidad de Articulo')),
                ('imagen', models.CharField(max_length=100, verbose_name='Descripcion de Articulo')),
            ],
            options={
                'ordering': ['marca', 'identificador'],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de Cargo')),
                ('nivel', models.CharField(max_length=10, verbose_name='Nivel de Cargo')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion de Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.IntegerField(verbose_name='Categoria de Cliente')),
                ('fecha_alta', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Alta')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cliente_persona', to='tienda.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo de movimiento')),
                ('numero', models.CharField(max_length=50, verbose_name='Numero de movimento')),
                ('fecha', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Movimiento')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimiento_cliente', to='tienda.cliente')),
            ],
            options={
                'ordering': ['numero', 'fecha'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_articulo', to='tienda.articulo')),
                ('movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_movimiento', to='tienda.movimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Legajo', models.IntegerField(verbose_name='Legajo de Empleado')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empleado_cargo', to='tienda.cargo')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empleado_persona', to='tienda.persona')),
            ],
        ),
    ]
