# Generated by Django 3.2.6 on 2021-09-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_rename_legajo_empleado_legajo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulo',
            options={'ordering': ['marca', 'nombre']},
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='identificador',
        ),
        migrations.AddField(
            model_name='articulo',
            name='nombre',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombre de articulo'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.CharField(max_length=100, verbose_name='Imagen de Articulo'),
        ),
    ]
