# Generated by Django 3.2.6 on 2021-09-22 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Autor')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido Autor')),
            ],
            options={
                'verbose_name_plural': 'Autores',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo del libro')),
                ('editorial', models.CharField(max_length=50, verbose_name='Editorial del libro')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='libro_autor', to='libreria.autor')),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
    ]
